### PR TITLE
update to MLJ 0.17.0

### PR DESCRIPTION
**Pull request by roland-KA**
I've updated tutorial 05 to MLJ 0.17.0 as well as all other packages to their most recent version.

Other changes:
- Use of the new pipeline syntax
- Simplified variable naming (and more in sync with Jupiter notebook)
- Changed several bullet points to section headings (so that they are accessible via the TOC)

### CODE REVIEW

**Comment by roland-KA** [comment]
There is an observation which I cannot explain:

- In Step 2 of '_Building a pipeline_ ...' the misclassification rate is calculated. In the Pluto notebook the resulting value is 0.427 whereas the executed Jupyter notebook shows 0.08. 
- In Step 'Output' of '_A composite model_ ...' the RMS is 5.0 and the MAE 3.25 in the Pluto notebook example, whereas the Jupyter notebook shows RMS = 3.84 and MAE = 2.46.

The last point may be explainable by different random sampling, but the first?

**Comment by ablaom** [comment]
Thanks for that. I'll investigate.

**Comment by ablaom** [comment]
Just noticing that if I use the old version of the pluto notebook, I get 0.08. So the problem is probably in this PR.

**Comment by ablaom** [comment]
Okay, if I try running the notebook in the current PR, Pluto spits the dummy:

```julia
 Warning: PlutoPkg: Failed to add/remove packages! Resetting package environment...
│   PLUTO_VERSION = v"0.17.5"
│   VERSION = v"1.6.5"
│   old_packages = 5-element Vector{String}: …
│   new_packages = 5-element Vector{String}: …
│   exception =
│    Unsatisfiable requirements detected for package AbstractPlutoDingetjes [6e696c72]:
│     AbstractPlutoDingetjes [6e696c72] log:
│     ├─AbstractPlutoDingetjes [6e696c72] has no known versions!
│     └─found to have no compatible versions left with PlutoUI [7f904dfe]
│       └─PlutoUI [7f904dfe] log:
│         ├─possible versions are: 0.1.0-0.7.30 or uninstalled
│         └─restricted to versions 0.7.30 by an explicit requirement, leaving only versions 0.7.30
│    Stacktrace:
│      [1] propagate_constraints!(graph::Pkg.Resolve.Graph, sources::Set{Int64}; log_events::Bool)
│        @ Pkg.Resolve /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Resolve/graphtype.jl:1048
│      [2] propagate_constraints! (repeats 2 times)
│        @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Resolve/graphtype.jl:989 [inlined]
│      [3] simplify_graph!(graph::Pkg.Resolve.Graph, sources::Set{Int64}; clean_graph::Bool)
│        @ Pkg.Resolve /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Resolve/graphtype.jl:1503
│      [4] simplify_graph! (repeats 2 times)
│        @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Resolve/graphtype.jl:1503 [inlined]
│      [5] resolve_versions!(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec})
│        @ Pkg.Operations /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:408
│      [6] targeted_resolve(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}, preserve::Pkg.Types.PreserveLevel)
│        @ Pkg.Operations /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1215
│      [7] _resolve
│        @ /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1221 [inlined]
│      [8] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}, new_git::Vector{Base.UUID}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform)
│        @ Pkg.Operations /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/Operations.jl:1236
│      [9] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform, kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
│        @ Pkg.API /Users/julia/buildbot/worker/package_macos64/build/usr/share/julia/stdlib/v1.6/Pkg/src/API.jl:204
│     [10] (::Pluto.var"#118#132"{Vector{String}, Pluto.Notebook, Pluto.IOListener})()
│        @ Pluto ~/.julia/packages/Pluto/xIB4x/src/packages/Packages.jl:166
│     [11] withinteractive(f::Pluto.var"#118#132"{Vector{String}, Pluto.Notebook, Pluto.IOListener}, value::Bool)
│        @ Pluto ~/.julia/packages/Pluto/xIB4x/src/packages/Packages.jl:494
│     [12] #117
│        @ ~/.julia/packages/Pluto/xIB4x/src/packages/Packages.jl:152 [inlined]
│     [13] withio(f::Pluto.var"#117#131"{Vector{String}, Pluto.Notebook, Pluto.IOListener}, ctx::Pkg.Types.Context, io::IOContext{IOBuffer})
│        @ Pluto.PkgCompat ~/.julia/packages/Pluto/xIB4x/src/packages/PkgCompat.jl:129
│     [14] (::Pluto.var"#111#124"{Pluto.Notebook, Pluto.IOListener, Vector{String}, Vector{String}, Bool, Bool})()
│        @ Pluto ~/.julia/packages/Pluto/xIB4x/src/packages/Packages.jl:151
│     [15] withtoken(f::Pluto.var"#111#124"{Pluto.Notebook, Pluto.IOListener, Vector{String}, Vector{String}, Bool, Bool}, token::Pluto.Token)
│        @ Pluto ~/.julia/packages/Pluto/xIB4x/src/evaluation/Tokens.jl:19
│     [16] sync_nbpkg_core(notebook::Pluto.Notebook; on_terminal_output::Pluto.var"#iocallback#140"{Pluto.ServerSession, Pluto.Notebook})
│        @ Pluto ~/.julia/packages/Pluto/xIB4x/src/packages/Packages.jl:103
│     [17] #138
│        @ ~/.julia/packages/Pluto/xIB4x/src/packages/Packages.jl:262 [inlined]
│     [18] withtoken(f::Pluto.var"#138#139"{Pluto.ServerSession, Pluto.Notebook}, token::Pluto.Token)
│        @ Pluto ~/.julia/packages/Pluto/xIB4x/src/evaluation/Tokens.jl:19
│     [19] sync_nbpkg(session::Pluto.ServerSession, notebook::Pluto.Notebook; save::Bool)
│        @ Pluto ~/.julia/packages/Pluto/xIB4x/src/packages/Packages.jl:253
│     [20] (::Pluto.var"#206#209"{Bool, Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, Pluto.ServerSession, Pluto.Notebook, Pluto.NotebookTopology})()
│        @ Pluto ~/.julia/packages/Pluto/xIB4x/src/evaluation/Run.jl:455
│     [21] macro expansion
│        @ ~/.julia/packages/Pluto/xIB4x/src/evaluation/Tokens.jl:101 [inlined]
│     [22] (::Pluto.var"#181#182"{Pluto.var"#206#209"{Bool, Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, Pluto.ServerSession, Pluto.Notebook, Pluto.NotebookTopology}})()
│        @ Pluto ./task.jl:411
└ @ Pluto ~/.julia/packages/Pluto/xIB4x/src/packages/Packages.jl:286
```

I installed Pluto in a fresh environment and called `using Pluto; Pluto.run(notebook="junk.pluto.jl")` to run the notebook. 

```julia
(jl_YvHJMC) pkg> st
      Status `/private/var/folders/4n/gvbmlhdc8xj973001s6vdyw00000gq/T/jl_YvHJMC/Project.toml`
  [c3e4b0f8] Pluto v0.17.5

julia> versioninfo()
Julia Version 1.6.5
Commit 9058264a69 (2021-12-19 12:30 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin19.6.0)
  CPU: Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-11.0.1 (ORCJIT, skylake)
Environment:
  JULIA_LTS_PATH = /Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia
  JULIA_PATH = /Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia
  JULIA_EGLOT_PATH = /Applications/Julia-1.6.app/Contents/Resources/julia/bin/julia
  JULIA_NUM_THREADS = 5
  JULIA_NIGHTLY_PATH = /Applications/Julia-1.7.app/Contents/Resources/julia/bin/julia
```

@roland-KA Any ideas what's going on?

**Comment by ablaom** [comment]
Okay, after this episode my julia installation had serious problems and I had to delete my .julia to resolve. After doing that the earlier problems seems to be resolved. 😌 . Will look again at this tomorrow.

**Comment by roland-KA** [comment]
> @roland-KA Any ideas what's going on?

Unfortunately not 😬 ... other users seem to have experienced [similar issues](https://stackoverflow.com/questions/64359283/why-am-i-getting-unsatisfiable-requirements-detected-for-package-http-error-wh). The package management is obviously completely confused in this situation and deleting `.julia` seems to help.

**Comment by roland-KA** [comment]
> Just noticing that if I use the old version of the pluto notebook, I get 0.08. So the problem is probably in this PR.

I can confirm that observation. A call to `fitted_params` on `my_pipe_mach` reveals the following: 

- In the old version of the notebook the following parameters have been learned:

```
intercept = Float64[
  -0.593257
  0.593257 
  -4.63513
]

standardizer = Dict{Symbol, Tuple{Float64, Float64}}
:sepal_length => (5.692, 0.791956)
:petal_width => (1.0368, 0.724072)
:petal_length => (3.4176, 1.73229)
:sepal_width => (3.0608, 0.458943)
``` 
- The new version has these parameters:

```
intercept = Float64[
  0.0667917
  0.0669801
  -0.138978
]

standardizer = Dict{Symbol, Tuple{Float64, Float64}}
:sepal_length => (5.692, 0.791956)
:petal_width => (1.0368, 0.724072)
:petal_length => (3.4176, 1.73229)
:sepal_width => (3.0608, 0.458943)
```

So the `Standardizer` learned in both versions identical parameters, whereas the `LogisticClassifier` came to completely different parameters (using the same dataset!).
That's weird 🤔.

**Comment by roland-KA** [comment]
Is my understanding correct, that the data which is used in steps 0, 1 and 2 (like `X, y`, `Xnew`, `Xnew2`) is purely dummy data? There is no learning of parameters involved? The only objective is the creation of a structure?

So the only training of the composed model with the Iris dataset takes place when calling `evaluate` at the end of step 2?

**Comment by roland-KA** [comment]
The only difference I could identify between the Pluto notebook and the Jupyter notebook up to now is a different version of `MLJLinearModels` used:

- Pluto
```
  [add582a8] MLJ v0.17.0
  [c6f25543] MLJDecisionTreeInterface v0.1.3
  [6ee0df7b] MLJLinearModels v0.6.0
```

- Jupyter
```
  [add582a8] MLJ v0.17.0
  [c6f25543] MLJDecisionTreeInterface v0.1.3
  [6ee0df7b] MLJLinearModels v0.5.7
```

**Comment by ablaom** [comment]
Ah-ha. That's it! 

If you do `linear = LogisticClassifier(scale_penalty_with_samples=false)` in the Pluto notebook, then you recover the same result.
https://github.com/JuliaAI/MLJLinearModels.jl/issues/108 . 

A little less cryptic for the reader would be to set `lambda = 0.001` (which gives a classification rate of ~~0.06~~  0.0733). I will do the same in the python notebook after updating MLJLinearModels. 

> Is my understanding correct, that the data which is used in steps 0, 1 and 2 (like X, y, Xnew, Xnew2) is purely dummy data? There is no learning of parameters involved? The only objective is the creation of a structure?

> So the only training of the composed model with the Iris dataset takes place when calling evaluate at the end of step 2?

Yes to all of that.

**Comment by roland-KA** [comment]
I've added the parameter `lambda = 0.001` to all uses of the `LogisticClassifier` in the Pluto notebook. So we should be in sync now.

**Comment by ablaom** [comment]
@roland-KA Thanks for your attention to detail that identified the lack of synchronisation and for the considerable help in diagnosis. 🙏🏾

**Comment by roland-KA** [comment]
> @roland-KA Thanks for your attention to detail that identified the lack of synchronisation 

Some people call it a slight tendency towards autism 😅 ... but sometimes it helps 😊.

> and for the considerable help in diagnosis. 🙏🏾

You are welcome!

**Pull request merged**
