### PR TITLE
add "improvements to 02_model"

### PR DESCRIPTION
**Pull request by roland-KA**
I've changed the Pluto notebook for part 02 so that it contains the "improvements to 02_model".

- Deleted the note to Pluto users about a possible error in section 'Save and retrieve a machine' since it isn't reproducible any more (updates to Pluto and/or MLJ seem to have solved the issue)
- For consistency reasons, I added the measure `misclassifiaction_rate` also to the fourth `evaluate!` in section 'Step 4 ...'

### CODE REVIEW

**Comment by roland-KA** [comment]
The Pluto notebook with the solutions to the exercises is now also functional:
- Added some section headings to make the different parts of the exercises more accessible via the TOC
- Ex. 6c - ii: Switched the order of the statements. Now the assignment `ntrees = 90` is done before `evaluate`. Seems to me more logical 😊.
- Ex. 8c: Added x- and y-labels to the sub-plots of `plt8`

**Comment by roland-KA** [comment]
I have a question on the `using` clauses in the notebook with the solutions (and in other notebooks): I had to add `using` clauses for `MLJDecisionTreeInterface` and `MLJClusteringInterface` (as well as to other interfaces in the remaining notebooks) in order to get them running.

It seems that these declarations are not necessary elsewhere (e.g. in the Jupyter notebooks). Do you have any idea why they are needed in the Pluto context?

**Comment by ablaom** [comment]
Thanks for this. And thanks for your patience - I have been on leave.

> It seems that these declarations are not necessary elsewhere (e.g. in the Jupyter notebooks). Do you have any idea why they are needed in the Pluto context?

No, I'm not sure but will merge this anyway.

**Comment by roland-KA** [comment]
> Thanks for this. And thanks for your patience - I have been on leave.
> 

Welcome back 😊

> > It seems that these declarations are not necessary elsewhere (e.g. in the Jupyter notebooks). Do you have any idea why they are needed in the Pluto context?
> 
> No, I'm not sure but will merge this anyway.

👍

I've added them because I got error messages that Julia doesn't know these packages. So they seem to be necessary in this context.

@fonsp explained that the only difference between executing a Julia program within Pluto or outside are the following points:
> - We evaluate code on a Distributed process
> - We evaluate code inside a module, not inside Main

So MLJ assumes probably that the code runs inside Main and not inside another module?

**Comment by ablaom** [comment]
> So MLJ assumes probably that the code runs inside Main and not inside another module?

No I don't think that is the issue. One can use `@load` in any global namespace. 

> It seems that these declarations are not necessary elsewhere (e.g. in the Jupyter notebooks). Do you have any idea why they are needed in the Pluto context?

In fact I don't believe the `using` statements are needed if you override Pluto's package management and use the environment that is provided under the `env/` directory in each tutorial. The issue is that executing `@load DecisionTreeClassifier pkg=DecisionTree` (in any global namespace) assumes that `MLJDecisionTreeInterface.jl` is in the active package environment, otherwise you get a complaint that it isn't. Since we explicitly add all required 3rd party packages into the supplied `env/`, this is not an issue for the Jupyter notebooks or REPL. However, your notebooks aren't activating that environment, so you need the `using` as a way to add it to the environment (`import` would also work and be safer).

So the way I see it, this is an artefact of Pluto taking over package management, which I must say was an ambitious idea 😄 Conflating the creation of a package environment with *loading* of code comes at a price. 

Does that make sense?

**Comment by roland-KA** [comment]
Ah of course, you are using a pre-defined environment (`env`). Somehow I didn't notice that before 🤦‍♂️🤓. 

Well then it's basically the same. Using REPL or Jupyter, the packages are specified via `env` whereas using Plutos built-in package management you have to list them in the notebook ... same thing in different places.

BTW I really appreciate Plutos package management in it's current form. It made my life easier, especially when sharing notebooks with other people (which I do a lot). The notebooks are now completely self-contained.  So, no more up-front preparation of Julia environments, communication and reconciliation of packages required etc. I can just send a Pluto notebook to anyone, and no matter which machine he/she is using or which Julia installation is present on that machine, the notebook runs. Of course it takes a bit longer to start, but that's a price I'm willing to pay.

The Pluto approach is more or less "what you see, is what you get", because all packages used are listed in the notebook. For that reason I put all `using/import` statements in _one_ cell at the _top_ of the notebook, so that every user can see at a glimpse how the environment looks like.

So, in the future I will have a look at the predefined `env` environment to see what is needed 😊👍.

**Pull request merged**
