### PR TITLE
Update tutorial 02:  .jl .ipynb, .unexcecuted.ipnb

### PR DESCRIPTION
**Pull request by ablaom**
So I believe #24 is resolved, as this PR demonstrates.

### CODE REVIEW

**Review by roland-KA — COMMENTED** [review]
For the moment I would like to stay with 1.6 because fonsp/Pluto.jl#1722 (which is basically JuliaLang/julia#41440) hasn't been resolved yet. Therefore several of the tutorials crash on a M1 machine using Julia 1.7. But a solution seems to be coming soon.

**Comment by ablaom** [comment]
That's fine. But as the pluto notebooks are not sharing a Manifest.toml with the other notebooks, you're fine for me to merge this PR, yes?

**Comment by roland-KA** [comment]
> That's fine. But as the pluto notebooks are not sharing a Manifest.toml with the other notebooks, you're fine for me to merge this PR, yes?

Yes, you are right, there are no dependencies, so you can merge this independent of the Pluto notebook.

But be aware, that the issues mentioned above are not Pluto specific. So also some of the Jupyter notebooks may not work properly on Julia 1.7/M1.

**Comment by ablaom** [comment]
> But be aware, that the issues mentioned above are not Pluto specific. So also some of the Jupyter notebooks may not work properly on Julia 1.7/M1.

Ah, thanks for letting me know! I may rethink this then.

**Pull request merged**
