### PR TITLE
adapt Pluto notebook for part 04 - now functional

### PR DESCRIPTION
**Pull request by roland-KA**
Pluto notebook for part 04 is functional:
- Uses now also the macro-free version of pipelines. So please check, if it's correct.
- As Pluto doesn't allow reuse of variable names, I have to change them accordingly. In this part I've used names wich are a bit more descriptive (it came in here more natural). So please have a look, if the names transport the ideas of the tutorial well or if some of them are perhaps rather misleading.
- In section 'Unbounded ranges and sampling' there is an incomplete sentence (third cell; I've marked the relevant parts). Please correct that.
-  Added x- and y-labels to the sub-plots of `tuned_plot`. The default values were too long and rendered thus unreadable.

### CODE REVIEW

**Comment by roland-KA** [comment]
There seems to be some problem with the Pluto version required. The version is for some reason restricted in this repository to 

`└─restricted by julia compatibility requirements to versions: [0.2.0, 0.3.0-0.3.6, 0.4.0-0.4.3, 0.5.0-0.5.21, 0.6.0-0.6.4, 0.7.0-0.7.10, 0.8.0-0.8.10, 0.9.0-0.9.11, 0.10.0-0.10.13, 0.11.0-0.11.14, 0.12.0-0.12.21, 0.14.0-0.14.9] or uninstalled — no versions left`

... but the most current version (which I'm using) is 0.17.1

**Comment by roland-KA** [comment]
... and just discovered a typo on one of the labels of `tuned_plot`: Instead of 
`ylabel!(tuned_plot[2, 1], "factors unbounded")`
it should read
`ylabel!(tuned_plot[2, 1], "lambda unbounded")`

**Comment by ablaom** [comment]
> Pluto notebook for part 04 is functional:

🎉 
> * Uses now also the macro-free version of pipelines. So please check, if it's correct.

✔️ 

> * As Pluto doesn't allow reuse of variable names, I have to change them accordingly. In this part I've used names wich are a bit more descriptive (it came in here more natural). So please have a look, if the names transport the ideas of the tutorial well or if some of them are perhaps rather misleading.

Seem good to me

> * In section 'Unbounded ranges and sampling' there is an incomplete sentence (third cell; I've marked the relevant parts). Please correct that.

Good catch! 
Fixed here and in the other tutorial at #13 

> * Added x- and y-labels to the sub-plots of `tuned_plot`. The default values were too long and rendered thus unreadable.

👍🏾

**Comment by ablaom** [comment]
Closed in favour of #13.

**Comment by ablaom** [comment]
> There seems to be some problem with the Pluto version required. 

Could you say more about where you get the conflict and post the full message please. I was not able to reproduce a conflict  in my testing.

**Comment by roland-KA** [comment]
> > There seems to be some problem with the Pluto version required.
> 
> Could you say more about where you get the conflict and post the full message please. I was not able to reproduce a conflict in my testing.

There are four checks running when I do a pull request. The first of them  failed yesterday with #12 (at this step: julia-actions/julia-buildpkg@v1; see 'Checks' on #12). 

It reported the following messages:
<details>
`Run julia-actions/julia-buildpkg@v1
4
Run julia --color=yes "$GITHUB_ACTION_PATH"/add_general_registry.jl
9
Run julia --color=yes --project=@. -e 'using Pkg; if VERSION >= v"1.1.0-rc1"; Pkg.build(verbose=true); else Pkg.build(); end'
12
   Cloning default registries into /home/runner/.julia/registries
13
   Cloning registry General from "https://github.com/JuliaRegistries/General.git"
14
25l    Fetching: [>                                        ]  0.0 %
15
    Fetching: [=========>                               ]  20.8 %
16
    Fetching: [=====================>                   ]  50.3 %
17
    Fetching: [================================>        ]  78.5 %
18
25h Resolving package versions...
19
ERROR: Unsatisfiable requirements detected for package Pluto [c3e4b0f8]:
20
 Pluto [c3e4b0f8] log:
21
 ├─possible versions are: [0.2.0, 0.3.0-0.3.6, 0.4.0-0.4.3, 0.5.0-0.5.21, 0.6.0-0.6.4, 0.7.0-0.7.10, 0.8.0-0.8.10, 0.9.0-0.9.11, 0.10.0-0.10.13, 0.11.0-0.11.14, 0.12.0-0.12.21, 0.14.0-0.14.9, 0.15.0-0.15.1, 0.16.0-0.16.4, 0.17.0-0.17.1] or uninstalled
22
 ├─restricted to versions 0.17.0-0.17 by an explicit requirement, leaving only versions 0.17.0-0.17.1
23
 └─restricted by julia compatibility requirements to versions: [0.2.0, 0.3.0-0.3.6, 0.4.0-0.4.3, 0.5.0-0.5.21, 0.6.0-0.6.4, 0.7.0-0.7.10, 0.8.0-0.8.10, 0.9.0-0.9.11, 0.10.0-0.10.13, 0.11.0-0.11.14, 0.12.0-0.12.21, 0.14.0-0.14.9] or uninstalled — no versions left
24
Stacktrace:
25
 [1] #propagate_constraints!#61(::Bool, ::Function, ::Pkg.GraphType.Graph, ::Set{Int64}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/GraphType.jl:1007
26
 [2] propagate_constraints! at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/GraphType.jl:948 [inlined]
27
 [3] #simplify_graph!#121(::Bool, ::Function, ::Pkg.GraphType.Graph, ::Set{Int64}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/GraphType.jl:1462
28
 [4] simplify_graph! at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/GraphType.jl:1462 [inlined] (repeats 2 times)
29
 [5] resolve_versions!(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}, ::Nothing) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:373
30
 [6] resolve_versions! at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:316 [inlined]
31
 [7] up(::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:1244
32
 [8] #up#31(::Pkg.Types.UpgradeLevel, ::Pkg.Types.PackageMode, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:203
33
 [9] up at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:176 [inlined]
34
 [10] #up#26 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:168 [inlined]
35
 [11] up at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:168 [inlined]
36
 [12] #instantiate#61(::Nothing, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Pkg.Types.Context) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:539
37
 [13] instantiate at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:537 [inlined]
38
 [14] #build#55(::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Pkg.Types.Context, ::Array{Pkg.Types.PackageSpec,1}) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:462
39
 [15] build at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:441 [inlined]
40
 [16] build at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:439 [inlined]
41
 [17] build() at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/API.jl:436
42
 [18] top-level scope at none:1
43
Error: Process completed with exit code 1.`
</details>

**Pull request closed without merging**
