### PR TITLE
Pluto notebook for part 02 adapted - is now functional

### PR DESCRIPTION
**Pull request by roland-KA**
Hi @ablaom, now the notebook for part 02 is ready.

There are a few points to look out for in this part:
- In 'Step 1', after loading the Iris dataset, there is no need to coerce the data. It seems that `CategoricalArrays` became smarter. When I did the conversion of the original tutorial about a week ago, there was still the need to do it. I left a comment in the notebook about this change (in case people are watching the YouTube video from 2020).
- In 'Warm start' I'm using the machine `mach` for further processing (not `mach3`). I think it actually doesn't matter which of both machines to use, but as Pluto has some problems with retrieving a machine from disk (see the note in 'Save and retrieve a machine'), it's safer to use `mach` here. And in case you wonder: If have inserted a few sub-titles in this section, to make the notebook more accessible from the TOC.
- Please have a look on the calculation of `misclassification_rate` in this notebook when you test it. On one run it calculated the value 0; on further runs the values seemed to be reasonable. I don't know why it returned 0 on the first run.

### CODE REVIEW

**Comment by roland-KA** [comment]
... and perhaps you leave this pull request open, so I can deliver the remaining parts on this basis?

**Comment by roland-KA** [comment]
Part 03 ist also ready:

- Here I've used the new macro-free mechanism for pipelines. So please have a closer look on the changes, since this mechanism is new to me.
- As long as this mechanism is not live, we have to add and import all packages manually (see cells at the top of the notebook below "Set-up"). Later on we can switch back to the (simpler) Pluto package management (just uncomment the cell which is already present).

**Comment by roland-KA** [comment]
In part 02 I've changed the code in "Warm restart", so that the output of the `fit!` operations shows in the notebook (and not in the terminal, where Pluto has been started).

**Comment by ablaom** [comment]
> Hi @ablaom, now the notebook for part 02 is ready.

Awesome, many thanks. They look very nice.

> There are a few points to look out for in this part:
> 
> * In 'Step 1', after loading the Iris dataset, there is no need to coerce the data. It seems that `CategoricalArrays` became smarter. When I did the conversion of the original tutorial about a week ago, there was still the need to do it. I left a comment in the notebook about this change (in case people are watching the YouTube video from 2020).

Thanks for flagging. I've fixed this in the other notebooks as well.

> * In 'Warm start' I'm using the machine `mach` for further processing (not `mach3`). I think it actually doesn't matter which of both machines to use, but as Pluto has some problems with retrieving a machine from disk (see the note in 'Save and retrieve a machine'), it's safer to use `mach` here. And in case you wonder: If have inserted a few sub-titles in this section, to make the notebook more accessible from the TOC.

👍🏾 

> * Please have a look on the calculation of `misclassification_rate` in this notebook when you test it. On one run it calculated the value 0; on further runs the values seemed to be reasonable. I don't know why it returned 0 on the first run.

The model is not reproducible and so this is not totally unexpected. I don't think it's a bug. Unfortunately we can't make this reproducible without using a different Flux chain `builder`, because you cannot currently pass an RNG to `Flux.dropout`. But I've flagged this [here](#11), thanks!

---

Unfortunately, the new pipeline type does not support type of transformations of the target, so I deleted that part of the tutorial, and added an explanation. Feel free to tweak this if you like. The plan is to have a separate model wrapper to handle target transformations. I guess I need to make this a higher priority 😄 .

I got some merge conflict headaches, and so am closing this in favour of #10, which I am going to merge. Probably best to make new PR's for each section anyway. I won't publicise the pluto tutorials too much until we get the pipeline stuff finished.

**Comment by roland-KA** [comment]
More people seem to run in that macro-related problem with Pluto when using `@pipeline` (see: [Pluto.jl #1658](https://github.com/fonsp/Pluto.jl/issues/1658)). I've added a comment within that issue, because I think it's also a general Pluto problem, that has to be resolved (since the code runs outside of Pluto without errors).

So it would be nice, if we could see progress on both fields 😊.

**Pull request closed without merging**
