### PR TITLE
adapt Pluto notebook for part 05 - issue with `@from_network` macro

### PR DESCRIPTION
**Pull request by roland-KA**
I've adapted part 05 of the tutorial. 

Unfortunately Pluto has also problems with the `@from_network` macro (which is the most relevant point of part 05 🙄). It's the same issue it had before with the `@pipeline` macro. Somehow Pluto doesn't understand the exported types coming from [MLJBase.jl/src/composition/abstract_types.jl](https://github.com/JuliaAI/MLJBase.jl/blob/a3f54292677008043fb406d15e975cfb18e607af/src/composition/abstract_types.jl).

Especially this part doesn't arrive in Pluto:
```
export MLJType, Model, Surrogate, Composite
for T in vcat(MMI.ABSTRACT_MODEL_SUBTYPES, COMPOSITE_TYPES, SURROGATE_TYPES)
    @eval(export $T)
end
```
So, in order to complete part 05 we have to wait until issue [Pluot.jl #1658](https://github.com/fonsp/Pluto.jl/issues/1658) is solved.

### CODE REVIEW

**Comment by roland-KA** [comment]
... and the first of the four automatic checks of this pull request didn't succeed again. It's the same error as before: `ERROR: Unsatisfiable requirements detected for package Pluto [c3e4b0f8]:`.

**Comment by ablaom** [comment]
> ... and the first of the four automatic checks of this pull request didn't succeed again. It's the same error as before: `ERROR: Unsatisfiable requirements detected for package Pluto [c3e4b0f8]:`.

Oh, now I see what you are referring to. I've actually no intention of supporting Julia 1.0, as MLJBase is now at 1.3. I'll update the CI matrix. Thanks for pointing this out!

**Comment by ablaom** [comment]
> So, in order to complete part 05 we have to wait until issue Pluot.jl #1658 is solved.

Okay, fair enough. Let's sit on this for now. Many thanks for your work on this!

**Comment by roland-KA** [comment]
Part 05 is now also completed as the issue with the macros is resolved.

In the introducing pipeline example, I've used here the classic `@pipeline` syntax so that I can use the Pluto package mechanism (in 'Set-up'). 

As soon as the `Pipline` type will be included in the official release of MLJ, I will adapt that and use the type instead of the macro.

**Comment by ablaom** [comment]
Thanks again for this!

Be great if in future PR's you do not commit the re-generated .png and .jlso files, as I'm having to revert them individually to resolve merge conflicts. Unless you have a better suggestion.

**Comment by roland-KA** [comment]
Sorry for the inconvenience. I will do the commits more selectively.

Wouldn't it be helpful to list these files in `.gitignore` as they are generated automatically? ... or not to store them in the repository at all?

**Comment by ablaom** [comment]
I think these are needed to enable static viewing of the pre-executed Jupyter notebooks, no?

**Comment by roland-KA** [comment]
Ah ok, that makes sense. So they have to be included of course.

**Pull request merged**
